services:
  auth:
    build: .
    container_name: auth
    image: auth
    depends_on:
      - db
    ports:
      - "8080:8080"
  db:
    image: postgres:latest
    container_name: db
    restart: always
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "${DB_PORT}:${DB_PORT}"
    volumes:
      - pg_data1:/var/lib/postgresql/data

volumes:
  pg_data1:
